FROM debian:buster

RUN apt-get update && apt-get install -y -q            \
        autoconf                                       \
        automake                                       \
        autotools-dev                                  \
        build-essential                                \
        ccache                                         \
        curl                                           \
        gdb                                            \
        git                                            \
        libtool                                        \
        patch                                          \
        wget                                           \
        libssl-dev                                     \
        libx11-dev                                     \
        libgtk2.0-dev                                  \
        libgtkglext1-dev                               \
        nano                                           \ 
        python3                                        \
        python3-pip                                    \
        ninja-build                                    \
        cmake                                          \        
        libnss3                                        \        
        libnspr4                                       \        
        libxss1                                        \        
        libatk-bridge2.0-0                             \        
        libxkbcommon-x11-0                             \        
        libgtk-3-0                                     \        
        libgtk-3-dev                                   \        
        libasound2                                     \        
  && apt-get clean
